### ISSUE TITLE
Multiple limit order and call order matching issue

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#453]
This issue has been described in [#338](https://github.com/bitshares/bitshares-core/issues/338#issuecomment-318808452), but it deserves a new ticket.

There is a bug when matching multiple limit orders with multiple call orders when there is a settlement price change.

https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/chain/db_market.cpp#L464:
```
bool filled_limit = false;
```
should be defined inside the loop, because `check_call_orders` is not only be called when a new `limit_order` is created, but will also be called when there is a price feed change, in this case there may be multiple `limit_order` objects as well as multiple `call_order` objects be processed. This has happened in the live chain for around 200 times, fixing this would require a hard fork.

[Some code in PR #341](https://github.com/bitshares/bitshares-core/pull/341/commits/aa60533269d7ca5e534bedb8a63ac4742d50164c) is related to this issue.

**Comment by abitmore** [comment]
Done with #829.

**Comment by a37h** [comment]
This issue still occurs in fresh built witness node.
```
267096ms th_a       application.cpp:515           handle_block         ] Got block: #250000 0003d09023fece9120e5c71763e2ca81f76a2629 time: 2015-10-22T10:32:45 transaction(s): 0 latency: 104905902096 ms from: bue  irreversible: 249978 (-22)
268161ms th_a       db_market.cpp:1064            check_call_orders    ] Multiple limit match problem (issue 453) occurred at block #258639
268161ms th_a       db_market.cpp:1064            check_call_orders    ] Multiple limit match problem (issue 453) occurred at block #258639
268161ms th_a       db_market.cpp:1064            check_call_orders    ] Multiple limit match problem (issue 453) occurred at block #258639
268325ms th_a       application.cpp:515           handle_block         ] Got block: #260000 0003f7a01ea704aab7bf34cf13a0df1eecf11961 time: 2015-10-22T19:02:57 transaction(s): 0 latency: 104875291325 ms from: dele-puppy  irreversible: 259976 (-24)
268517ms th_a       db_market.cpp:1064            check_call_orders    ] Multiple limit match problem (issue 453) occurred at block #261318
269541ms th_a       application.cpp:515           handle_block         ] Got block: #270000 00041eb0e47f4dfc63f723a1cb6cbfc178f5182c time: 2015-10-23T03:24:39 transaction(s): 0 latency: 104845190541 ms from: datasecuritynode  irreversible: 269973 (-27)
```

Should I just ignore it?

**Comment by abitmore** [comment]
@a37h the issue has been fixed. The logging will be removed when we have time (not a priority so far).
