### ISSUE TITLE
ambiguous conversion for functional-style cast from 'unsigned long' to 'fc::variant'

### ISSUE THREAD

**Issue by kenneth** [bitshares/bitshares-core#800]
build error

```
[ 70%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/node.cpp.o
In file included from /bitshares/bitshares-core/libraries/net/node.cpp:61:
In file included from /bitshares/bitshares-core/libraries/fc/include/fc/thread/thread.hpp:5:
In file included from /bitshares/bitshares-core/libraries/fc/include/fc/thread/task.hpp:2:
In file included from /bitshares/bitshares-core/libraries/fc/include/fc/thread/future.hpp:5:
In file included from /bitshares/bitshares-core/libraries/fc/include/fc/exception/exception.hpp:6:
In file included from /bitshares/bitshares-core/libraries/fc/include/fc/log/logger.hpp:6:
In file included from /bitshares/bitshares-core/libraries/fc/include/fc/log/log_message.hpp:8:
In file included from /bitshares/bitshares-core/libraries/fc/include/fc/variant_object.hpp:2:
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:334:27: error: ambiguous conversion for
      functional-style cast from 'unsigned long' to 'fc::variant'
           return *this = variant( fc::forward<T>(v) );
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/bitshares/bitshares-core/libraries/net/node.cpp:1853:28: note: in instantiation of function template
      specialization 'fc::variant::operator=<unsigned long>' requested here
      user_data["bitness"] = sizeof(void*) * 8;
                           ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:206:9: note: candidate constructor
        variant( float val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:207:9: note: candidate constructor
        variant( uint8_t val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:208:9: note: candidate constructor
        variant( int8_t val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:209:9: note: candidate constructor
        variant( uint16_t val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:210:9: note: candidate constructor
        variant( int16_t val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:211:9: note: candidate constructor
        variant( uint32_t val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:212:9: note: candidate constructor
        variant( int32_t val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:213:9: note: candidate constructor
        variant( uint64_t val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:214:9: note: candidate constructor
        variant( int64_t val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:215:9: note: candidate constructor
        variant( double val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:216:9: note: candidate constructor
        variant( bool val, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:222:9: note: candidate constructor
        variant( const variant&, uint32_t max_depth = 1 );
        ^
/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:223:9: note: candidate constructor
        variant( variant&&, uint32_t max_depth = 1 );
        ^
1 error generated.
make[2]: *** [libraries/net/CMakeFiles/graphene_net.dir/node.cpp.o] Error 1
make[1]: *** [libraries/net/CMakeFiles/graphene_net.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jmjatlanta** [comment]
Is your operating system OSX? I'm researching the same thing for issue #799 .

**Comment by cifer-lee** [comment]
Got the same issue:

OS: OSX High Sierra

Compiler:
```
➜  bitshares-core git:(master) ✗ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

boost version: 1.60
Openssl: 1.0.2

**Comment by cifer-lee** [comment]
btw, maybe I could fix it, @jmjatlanta are you working on it already?

**Comment by jmjatlanta** [comment]
Yes. The problem is a difference in size_t between mac and linux. I have modified bitshares-fc to account for this. I am testing it now.

**Comment by kenneth** [comment]
@jmjatlanta the newest code have this error ,maybe something change wrong。I can build success in last version.

my MacBook is High Sierra
boost 1.60
OPENSSL_VERSION = 1.0.2o

```
 ✗ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```



```
-- Using custom FindBoost.cmake
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   thread
--   iostreams
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
-- Using custom FindBoost.cmake
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   coroutine
-- Configuring BitShares on OS X
-- Configuring project fc located in: /bitshares/bitshares-core/libraries/fc
-- Configuring fc to build on Unix/Apple
-- Using custom FindBoost.cmake
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
--   coroutine
** websocketpp

=========== Used Build Configuration =============

-- ENABLE_CPP11        = ON
-- BUILD_EXAMPLES      = OFF
-- BUILD_TESTS         = OFF

-- WEBSOCKETPP_ROOT    = /bitshares/bitshares-core/libraries/fc/vendor/websocketpp
-- WEBSOCKETPP_BIN     = /bitshares/bitshares-core/libraries/fc/vendor/websocketpp/bin
-- WEBSOCKETPP_LIB     = /bitshares/bitshares-core/libraries/fc/vendor/websocketpp/lib
-- Install prefix      = /usr/local

-- WEBSOCKETPP_BOOST_LIBS        =
-- WEBSOCKETPP_PLATFORM_LIBS     =
-- WEBSOCKETPP_PLATFORM_TLS_LIBS =

-- OPENSSL_FOUND        = TRUE
-- OPENSSL_INCLUDE_DIR     = /usr/local/opt/openssl/include
-- OPENSSL_LIBRARIES = /usr/local/opt/openssl/lib/libssl.a;/usr/local/opt/openssl/lib/libcrypto.a
-- OPENSSL_VERSION = 1.0.2o

-- zlib found
-- bzip2 found
-- LOG_LONG_API: ON
--
--      LOGGING LONG API CALLS
--           MAX  MS: 1000
--           WARN MS: 750
--
-- Finished fc module configuration...
-- Graphene database unity build enabled
```

**Comment by jmjatlanta** [comment]
I do not see your error. Perhaps the post was cut off? One option is to use a site like

http://pastebin.com

and post your entire build output. Provide a link and I'll take a look.

**Comment by kenneth** [comment]
@jmjatlanta 


```
➜  bitshares-core git:(92eb45cb) ✗ make
[  3%] Built target project_secp256k1
[  6%] Built target project_editline
[ 32%] Built target fc
[ 33%] Built target real128_test
[ 40%] Built target all_tests
[ 41%] Built target log_test
[ 42%] Built target ecc_test
[ 42%] Built target blinding_test
[ 42%] Built target hmac_test
[ 43%] Built target task_cancel_test
[ 44%] Built target blind
[ 44%] Built target api
[ 45%] Built target bloom_test
[ 46%] Built target bip_lock
[ 48%] Built target graphene_db
[ 49%] Built target deterministic_openssl_rand
[ 50%] Built target cat-parts
File "/Volumes/bitshares/bitshares-core/libraries/chain/include/graphene/chain/hardfork.hpp" up-to-date with .d directory
[ 50%] Built target build_hardfork_hpp
[ 66%] Built target graphene_chain
[ 69%] Built target graphene_utilities
[ 70%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/node.cpp.o
In file included from /Volumes/bitshares/bitshares-core/libraries/net/node.cpp:61:
In file included from /Volumes/bitshares/bitshares-core/libraries/fc/include/fc/thread/thread.hpp:5:
In file included from /Volumes/bitshares/bitshares-core/libraries/fc/include/fc/thread/task.hpp:2:
In file included from /Volumes/bitshares/bitshares-core/libraries/fc/include/fc/thread/future.hpp:5:
In file included from /Volumes/bitshares/bitshares-core/libraries/fc/include/fc/exception/exception.hpp:6:
In file included from /Volumes/bitshares/bitshares-core/libraries/fc/include/fc/log/logger.hpp:6:
In file included from /Volumes/bitshares/bitshares-core/libraries/fc/include/fc/log/log_message.hpp:8:
In file included from /Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant_object.hpp:2:
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:334:27: error: ambiguous conversion for functional-style cast from 'unsigned long' to
      'fc::variant'
           return *this = variant( fc::forward<T>(v) );
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/bitshares/bitshares-core/libraries/net/node.cpp:1853:28: note: in instantiation of function template specialization
      'fc::variant::operator=<unsigned long>' requested here
      user_data["bitness"] = sizeof(void*) * 8;
                           ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:206:9: note: candidate constructor
        variant( float val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:207:9: note: candidate constructor
        variant( uint8_t val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:208:9: note: candidate constructor
        variant( int8_t val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:209:9: note: candidate constructor
        variant( uint16_t val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:210:9: note: candidate constructor
        variant( int16_t val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:211:9: note: candidate constructor
        variant( uint32_t val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:212:9: note: candidate constructor
        variant( int32_t val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:213:9: note: candidate constructor
        variant( uint64_t val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:214:9: note: candidate constructor
        variant( int64_t val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:215:9: note: candidate constructor
        variant( double val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:216:9: note: candidate constructor
        variant( bool val, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:222:9: note: candidate constructor
        variant( const variant&, uint32_t max_depth = 1 );
        ^
/Volumes/bitshares/bitshares-core/libraries/fc/include/fc/variant.hpp:223:9: note: candidate constructor
        variant( variant&&, uint32_t max_depth = 1 );
        ^
1 error generated.
make[2]: *** [libraries/net/CMakeFiles/graphene_net.dir/node.cpp.o] Error 1
make[1]: *** [libraries/net/CMakeFiles/graphene_net.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by jmjatlanta** [comment]
It looks as if you do not have the changes I made in the bitshares-fc PR. Go to the libraries/fc directory and follow the instructions that are displayed after clicking the link near the bottom of the following page, where it says "view command line instructions":

https://github.com/bitshares/bitshares-fc/pull/35

**Comment by abitmore** [comment]
@jmjatlanta I think it's OK to merge that PR.

**Comment by jmjatlanta** [comment]
Merge completed. This change now exists in the master branch of bitshares-fc. Therefore, if you wish to try it out, ignore the instructions given above and:
* ``cd libraries/fc``
* ``git checkout master`` (if you are not already on the master branch of bitshares-fc)
* ``git pull``

**Comment by kenneth** [comment]
@jmjatlanta  Thank you for your work , the fc library have compile pass。 but I meet a new error。

```
➜  bitshares-core git:(92eb45cb) ✗ make
[  3%] Built target project_secp256k1
[  6%] Built target project_editline
[ 32%] Built target fc
[ 33%] Built target real128_test
[ 40%] Built target all_tests
[ 41%] Built target log_test
[ 42%] Built target ecc_test
[ 42%] Built target blinding_test
[ 42%] Built target hmac_test
[ 43%] Built target task_cancel_test
[ 44%] Built target blind
[ 44%] Built target api
[ 45%] Built target bloom_test
[ 46%] Built target bip_lock
[ 48%] Built target graphene_db
[ 49%] Built target deterministic_openssl_rand
[ 50%] Built target cat-parts
[ 50%] Built target build_hardfork_hpp
[ 66%] Built target graphene_chain
[ 69%] Built target graphene_utilities
[ 72%] Built target graphene_net
[ 73%] Built target graphene_debug_witness
[ 74%] Built target graphene_grouped_orders
[ 74%] Built target graphene_market_history
[ 74%] Built target graphene_account_history
[ 77%] Built target graphene_app
[ 78%] Built target graphene_egenesis_none
[ 78%] Built target embed_genesis
[ 79%] Built target graphene_egenesis_full
[ 80%] Built target graphene_egenesis_brief
[ 81%] Built target graphene_witness
[ 81%] Built target graphene_elasticsearch
[ 81%] Built target graphene_delayed_node
[ 81%] Built target graphene_snapshot
[ 82%] Built target graphene_es_objects
[ 83%] Built target graphene_wallet
[ 83%] Built target member_enumerator
[ 84%] Built target cli_wallet
[ 85%] Built target convert_address
[ 86%] Built target get_dev_key
[ 87%] Built target genesis_update
[ 88%] Built target witness_node
[ 88%] Built target delayed_node
[ 89%] Built target js_operation_serializer
[ 90%] Built target size_checker
[ 91%] Built target performance_test
[ 91%] Building CXX object tests/CMakeFiles/cli_test.dir/cli/main.cpp.o
/Volumes/BlockDev/bitshares/bitshares-core/tests/cli/main.cpp:112:76: error: invalid operands to binary expression
      ('__bind<int &, sockaddr *, unsigned long>' and 'int')
   if (bind(socket_fd, (struct sockaddr*)&sin, sizeof(struct sockaddr_in)) == -1)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~
1 error generated.
make[2]: *** [tests/CMakeFiles/cli_test.dir/cli/main.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/cli_test.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Arthur111** [comment]
I get the same error after applying the 2 fixes on fc

macOS 10.13.4
Boost 1_63_0
Openssl 1.0.2o

**Comment by abitmore** [comment]
@kenneth it has been fixed in latest `develop` branch of this repository.

**Comment by kenneth** [comment]
@abitmore this patch is really work, but i still  meet a ld architecture problem。
when i  use python pip i can use ARCHFLAGS="-arch x86_64" to solve it but now i can't 。
I don't know why do you have any suggestions?

```
➜  bitshares-core git:(develop) ✗  make
[  3%] Built target project_secp256k1
[  6%] Built target project_editline
[ 32%] Built target fc
[ 33%] Built target real128_test
[ 40%] Built target all_tests
[ 41%] Built target log_test
[ 42%] Built target ecc_test
[ 42%] Built target blinding_test
[ 42%] Built target hmac_test
[ 43%] Built target task_cancel_test
[ 44%] Built target blind
[ 44%] Built target api
[ 45%] Built target bloom_test
[ 46%] Built target bip_lock
[ 48%] Built target graphene_db
[ 49%] Built target deterministic_openssl_rand
[ 50%] Built target cat-parts
[ 50%] Built target build_hardfork_hpp
[ 66%] Built target graphene_chain
[ 69%] Built target graphene_utilities
[ 72%] Built target graphene_net
[ 73%] Built target graphene_debug_witness
[ 74%] Built target graphene_grouped_orders
[ 74%] Built target graphene_market_history
[ 74%] Built target graphene_account_history
[ 77%] Built target graphene_app
[ 78%] Built target graphene_egenesis_none
[ 78%] Built target embed_genesis
[ 79%] Built target graphene_egenesis_full
[ 80%] Built target graphene_egenesis_brief
[ 81%] Built target graphene_witness
[ 81%] Built target graphene_elasticsearch
[ 81%] Built target graphene_delayed_node
[ 81%] Built target graphene_snapshot
[ 82%] Built target graphene_es_objects
[ 83%] Built target graphene_wallet
[ 83%] Built target member_enumerator
[ 84%] Built target cli_wallet
[ 85%] Built target convert_address
[ 86%] Built target get_dev_key
[ 87%] Built target genesis_update
[ 88%] Built target witness_node
[ 88%] Built target delayed_node
[ 89%] Built target js_operation_serializer
[ 90%] Built target size_checker
[ 91%] Built target performance_test
[ 91%] Built target cli_test
[ 92%] Built target app_test
[ 93%] Built target chain_bench
[ 94%] Linking CXX executable chain_test
Undefined symbols for architecture x86_64:
  "fc::api<graphene::wallet::wallet_api, fc::identity_member>::register_api(fc::api_connection&) const", referenced from:
      vtable for fc::api<graphene::wallet::wallet_api, fc::identity_member> in libgraphene_wallet.a(api_documentation.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tests/chain_test] Error 1
make[1]: *** [tests/CMakeFiles/chain_test.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by cifer-lee** [comment]
@abitmore No, I had encountered and passed the `fc::variant` and `invalid operands` errors, then built success, no latest error.

And my environment is identity with @kenneth, no idea why his fail...

**Comment by Arthur111** [comment]
I get the same error as kenneth after the 2 previous bug fixed.

macOS 10.13.4
Boost 1_63_0
Openssl 1.0.2o

**Comment by abitmore** [comment]
Perhaps this would help: https://stackoverflow.com/questions/19821041/g-ld-symbols-not-found-for-architecture-x86-64 . I don't know how to configure that in cmake, wish someone among you could help and submit a PR if needed.

**Comment by jmjatlanta** [comment]
I modified the CMakeLists.txt file to statically link tcmalloc, and now I am getting the "undefined symbols" error. I cleaned my environment and am trying again. As I did nothing with git between builds, I am guessing this has something to do with a file not being cleaned up in the build environment. The error message points to libgraphene_wallet.a(api_documentation.cpp.o), so I'm starting there.

**Comment by abitmore** [comment]
Thank you @jmjatlanta.

I'm not sure whether editing a comment will send out notifications, so just doing it here again: @cifer-lee @Arthur111 @kenneth please check #817 .

**Comment by cifer-lee** [comment]
Wonderful work~ thanks @jmjatlanta

**Comment by kenneth** [comment]
@abitmore @jmjatlanta @cifer-lee @Arthur111 
You are all compile pass ,just leave me alone in 94%。It let me so frustration！

**Comment by Arthur111** [comment]
Usually a project must not be put in the internet before its compilation is ok.This case was a nightmare.
Apply the fixes describe above.
(i think you are missing some "git ..." stuff.)

**Comment by abitmore** [comment]
@kenneth I've merged #817. Please check again.
```
git checkout develop
git pull
```

**Comment by kenneth** [comment]
@abitmore  thank you ,I have compile pass!

**Comment by cwyyprog** [comment]
When I compile this project on the mac os 10.13.4, I got the same error:

```
/Users/qixiaoli/bitshares-core/libraries/fc/include/fc/variant.hpp:334:27: error: ambiguous conversion for functional-style cast from 'unsigned long' to 'fc::variant'
           return *this = variant( fc::forward<T>(v) );
```
and many 
```
/Users/qixiaoli/bitshares-core/programs/size_checker/main.cpp:61:22: error: use of overloaded operator '=' is ambiguous (with operand types 'fc::variant' and 'unsigned long')
      vo["mem_size"] = sizeof( Type );
```
error.
This issue seems not solved and should be reopened. 
Compiler info:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
boost version: 1.60
openssl version: 1.0.2o_1

**Comment by abitmore** [comment]
@cwyyprog `git checkout develop`

**Comment by abitmore** [comment]
@cwyyprog 
```
git checkout develop
git pull
git submodule update --init --recursive
```
