### ISSUE TITLE
ninja build fails

### ISSUE THREAD

**Issue by ihla** [bitshares/bitshares-core#859]
ninja: error: 'libraries/fc/vendor/editline/src/project_editline-build/src/.libs/libeditline.a', needed by 'libraries/fc/tests/real128_test', missing and no known rule to make it

when I run 'ninja fc' and then 'ninja' the build works

**Comment by ihla** [comment]
fix in CMakeLists.txt [here](https://github.com/bitshares/bitshares-fc/pull/39)

**Comment by abitmore** [comment]
Fixed by https://github.com/bitshares/bitshares-fc/pull/39.

**Comment by abitmore** [comment]
Need to bump FC version.

**Comment by abitmore** [comment]
This has been fixed in develop branch.

**Comment by crazybits** [comment]
has this fixed applied to all branch? still encounter issue on release branch on MacOS

> No rule to make target `libraries/fc/vendor/editline/src/project_editline-build/src/.libs/libeditline.a', needed by `programs/witness_node/witness_node'

**Comment by abitmore** [comment]
@crazybits I think your issue is different.

**Comment by abitmore** [comment]
@crazybits please create a new `build error` issue and link it to this issue. Thanks.
