### ISSUE TITLE
Review and backport EOS PR 3392 packing/unpacking array-like types

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#995]
https://github.com/EOSIO/eos/pull/3392

**Comment by pmconrad** [comment]
Need to be careful with introducing new limits here, to remain compatible with existing code.
I *think* the limits used by EOS should be safe because they're greater than the current max blocksize.

**Comment by jmjatlanta** [comment]
May be related: https://github.com/EOSIO/eos/pull/2424

**Comment by jmjatlanta** [comment]
Note: This is not necessarily a hardfork change, but is an area where we need to use extreme caution. See the PR https://github.com/bitshares/bitshares-fc/pull/55 for more information

**Comment by jmjatlanta** [comment]
I have taken a step back to re-evaluate. I am adding notes here as a memory aide. I believe the major intent in eos was threefold:

1. To handle the serialization and de-serialization of large data files (i.e. persisted database files)
2. To make sure size limits are consistent between pack and unpack. If it fit going in, it should fit coming out.
3. Set limits that are easier to understand both in code and in documentation.

The part that requires caution relates to backward-compatibility. The methods must be able to interpret incoming bytes the same as before. Unit tests will need to be complete and exhaustive, with the ability to read (and for testing, create) byte streams that exactly match the results of the previous pack/unpack versions (need to figure out how best to accomplish this). Edge cases exist at extremely small objects, overly large objects and collections with both small and large numbers of elements.

Also, if the limits imposed are different than before, this change requires hardfork protection.

**Comment by pmconrad** [comment]
Just realized that `sizeof` as used in current fc implementation may be platform-dependent and therefore also endangers consensus. We should fix this in the next hardfork, using limits that are beyond current block size.

**Comment by jmjatlanta** [comment]
Another option to prevent consensus size differences (suggested by @pmconrad) is to prevent network messages above a certain size. This would "catch the problem at the door", and not affect consensus at the pack/unpack level. This has been done as part of pull https://github.com/bitshares/bitshares-fc/pull/100

Should it be decided that pull 100 fixes this issue as well, the following questions remain:

- Should we remove now unnecessary FC_ASSERTs related to max pack/unpack sizes?
    - In my opinion, yes.
- Does pull 100 also fix the ``sizeof()`` consensus worry?
    - I believe the answer is "mostly". This code would no longer have size checking, so would be clean. The code in the networking layer would be susceptible to breaking consensus on messages very close to the maximum.

I am looking forward to other's thoughts.

**Comment by jmjatlanta** [comment]
@pmconrad This ticket fixed the problem of serialization checks, but the sizeof problem probably still exists in areas. Should a new ticket be created, or should we just use this one?

**Comment by jmjatlanta** [comment]
Fixed by bitshares/bitshares-fc/pull/100 and (to a lesser degree) bitshares/bitshares-fc/pull/103. This exposed another issue detailed at #1540

**Comment by abitmore** [comment]
I guess this can be put into next feature release?

**Comment by jmjatlanta** [comment]
Good question. Neither bitshares/bitshares-fc/pull/103 nor bitshares/bitshares-fc/pull/100 have hardfork protection, as the rules should not have changed.

The FC_ASSERTs removed in bitshares/bitshares-fc/pull/103 have been replaced by the 1 FC_ASSERT added in bitshares/bitshares-fc/pull/100.

Please feel free to put a second set of eyes on those changes.
